### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LocalCodes** [ahqsoftwares/tickets-discord#4]
Is there an option for newly created channels with this package to be synced with a category's permissions?

**Comment by ahqsoftwares** [comment]
actually there isnt any option for logging newly created channels

It will be added with version 4.1.0 or above

**Comment by LocalCodes** [comment]
Sorry, I misworded. What I meant, for ticket channels created, is it possible for it to be created in a dedicated category and have that new channel the package created synced with permissions?

**Comment by ahqsoftwares** [comment]
Actually it is not implemented.
If you like i can add it

**Comment by LocalCodes** [comment]
Yeah that would be great. It adds onto customization. :-) 

thank u

**Comment by ahqsoftwares** [comment]
Ok 👍

**Comment by LocalCodes** [comment]
Thank you! I plan on using your package for my non-profit organization, let me know if you'd like to check us out! ^-^

**Comment by ahqsoftwares** [comment]
No problem

**Comment by ahqsoftwares** [comment]
The following has been added to version 4.0.1

**Comment by LocalCodes** [comment]
Hey, so I checked over the commits and it appears that you set its own permissions? Not that it syncs with the parent category.
For reference: https://stackoverflow.com/questions/53129347/create-synced-category-and-channel 

Also it doesn't seem like you can customise it to where new channels are placed into a dedicated category?

**Comment by ahqsoftwares** [comment]
Actually the main problem is that this package is in use with a project scrtch for discord so it cannot be major updated

**Comment by LocalCodes** [comment]
Fair enough. I guess I can use ModMail by Dragory.

**Comment by ahqsoftwares** [comment]
Ok
